# BetterRTP plugin by SuperRonanCraft! (Join my Public Server mc.RonanCraft.net) #
# Need help? go to https://ronancraft.net/discord! #

Language-File: 'en.yml'

Settings:
  ## Output to console some debugging info
  Debugger: false
  ## Respect WorldGuard areas # IN-PROGRESS
  RespectWorldGuard: false
  ## Respect GriefPrevention areas # COMING SOON
  RespectGriefPrevention: false
  ## Respect Faction areas # COMING SOON
  RespectSavageFactions: false
  ## Must be a positive integer #
  MinRadius: 25
  ## Maximum amount of tries before BetterRTP gives up and sends a NotSafeMessage #
  MaxAttempts: 15
  ## Enabled or disabled cooldown timer, time is in SECONDS #
  Cooldown:
    Enabled: true
    Time: 10
  ## Time between command and actually rtp'ing, time is in SECONDS. Set to "0" to disable delay timer #
  Delay:
    Enabled: true
    Time: 5
    CancelOnMove: true
  Particles:
    Enabled: true
    Type: 'PORTAL' #list of particle types at https://github.com/ByteZ1337/ParticleLib/blob/master/src/main/java/xyz/xenondevs/particle/ParticleEffect.java
    Amount: 180
    Shape: 'SCAN' #Types available are "Scan, Teleport and Explosive"
  DisableUpdater: false

Default:
  UseWorldBorder: false
  ## "Biomes: []" means all biomes are allowed! #
  ## Biomes are optional, more biomes at https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/block/Biome.html #
  Biomes: []
  MaxRadius: 1000
  MinRadius: 10
  ## If "UseWorldBorder" is set to true above, these values WILL be ignored! Except Biomes! #
  CenterX: 0
  CenterZ: 0

## Blocks BetterRTP will NOT teleport onto. More Blocks at: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html #
BlacklistedBlocks:
  - stationary_water
  - stationary_lava
  - water
  - flowing_water
  - lava
  - flowing_lava
  - cactus
  - leaves
  - leaves_2
  - air
  - void_air

## Worlds to NOT allow /rtp in, unless there is an override to another enabled world #
DisabledWorlds:
  - prison
  - creative

## Worlds you want to have a custom min/max and spawn center in #
## [MaxRadius] and [MinRadius] MUST be positive! These cannot be equal to each other!
CustomWorlds:
  - custom_world_1:
      UseWorldBorder: false
      ## If UseWorldBorder is true, everything will be ignored EXEPT "MinRadius"!
      MaxRadius: 1000
      MinRadius: 100
      CenterX: 0
      CenterZ: 0
  - other_custom_world:
      MaxRadius: 100000
      MinRadius: 1000
      CenterX: 123
      CenterZ: -123
      ## Biomes are optional, but useful! More biomes: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/block/Biome.html
      Biomes:
        - 'desert'
        - 'forest'

## Override a world and rtp a player executing the command in one world, to another
Overrides:
  #FORMAT - <CURRENT>:<OTHER>
  - master_world: 'world'
  - creative_world: 'world'

WorldType: # Available types are NORMAL, NETHER
  - world: NORMAL
  - world_nether: NETHER
  - world_the_end: NORMAL
